# Generated by Django 5.0.1 on 2024-01-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_foodsmodel_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsmodel',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
