# Generated by Django 5.0.1 on 2024-01-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_eatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatmodel',
            name='name',
            field=models.CharField(default=1, max_length=221),
            preserve_default=False,
        ),
    ]
