# Generated by Django 5.0.1 on 2024-01-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefmodel',
            old_name='profesion',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='chefmodel',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
