# Generated by Django 5.0.1 on 2024-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_taommodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events')),
                ('data', models.CharField(max_length=221)),
                ('name', models.CharField(max_length=221)),
                ('location', models.CharField(max_length=221)),
            ],
        ),
        migrations.DeleteModel(
            name='TaomModel',
        ),
    ]
