# Generated by Django 5.0.1 on 2024-01-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_eventmodels_delete_taommodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventModels',
        ),
        migrations.DeleteModel(
            name='FodsModel',
        ),
    ]
