# Generated by Django 5.0.1 on 2024-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
