# Generated by Django 5.0.1 on 2024-01-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chef')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=221)),
                ('description', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Chefs',
                'verbose_name_plural': 'Chef',
            },
        ),
    ]
