# Generated by Django 5.0.1 on 2024-01-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_chefmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChefModel',
        ),
    ]
